services:
  - type: web
    name: nba-minimum-total-dashboard
    env: python
    buildCommand: pip install -r requirements_web.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
