services:
  - type: web
    name: nba-minimum-total-dashboard
    env: python
    runtime: python-3.11.9
    plan: free
    buildCommand: pip install -r requirements_web.txt
    startCommand: gunicorn app:app
